baseurl = "https://jjmtaylor.com/"
languageCode = "en-us"
title = "James JM Taylor"
theme = "hugo-strata-theme"
disqusShortname = "jjmtaylor"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-79422202-2"
# Define how many posts should appear on a site
paginate = 5

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "James Taylor"
	description = "Blog and Portfolio for James Taylor, a native and hybrid android and iOS mobile developer."

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Hi!**  I'm James, a dedicated\n polyglot mobile developer\n based in Portland, OR."
		# The icons will be shown if you enter your username
		twitter = "James43289009"
		github = "jamesjmtaylor"
		dribbble = ""
		facebook = "James.Jordan.Moody.Taylor"
		googleplus = ""
		flickr = ""
		linkedin = "jamesjmtaylor"

		copyright = [
			"&copy; James Taylor",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Why me?"
		content = "Because you want a disciplined, innovative worker with a mean streak for pragmatism and a lifelong passion for learning. I take great pride in delivering delightful experiences to users of my mobile applications, and learned Sketch, Zeplin, and Lottie to make up for the lack of a designer on my personal projects. I quickly realized  though that an app is all for naught without a solid backend to support it.  So I used the Java from my native Android development to jumpstart into Spring Boot server development.  Now, with full command of the stack I've returned to delivering holistic applications for my users."
	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			destination = "https://www.bowflex.com/max-trainer/"
			preview = "https://jjmtaylor.com/images/thumbs/bowflex.jpg"
			title = "Bowflex Max Intelligence (iOS & aOS)"
			description = "The Max Intelligence™ App offers the guidance and motivation you need by providing in-depth analytics and awards, helping you celebrate milestones, achievements, personal bests, and keeping track of time, calories burned, and more."

		[[params.portfolio.gallery]]
			destination = "https://evercharge.com/"
			preview = "https://jjmtaylor.com/images/thumbs/evercharge.png"
			title = "Evercharge (iOS & aOS)."
			description = "Dynamic electric vehicle (EV) charging solutions for commercial fleets, multi-family residential properties, and single-family homes."

		[[params.portfolio.gallery]]
			destination = "https://youtu.be/7_5AZIRh2VE?t=64"
			preview = "https://jjmtaylor.com/images/thumbs/find.jpg"
			title = "Steelcase Personal Assistant (iOS & aOS)."
			description = "Together with Workplace Advisor Subscription and Microsoft Office 365, the Find app makes finding and reserving the best workspaces quick and simple."

		[[params.portfolio.gallery]]
			destination = "https://www.jenie.com/"
			preview = "https://jjmtaylor.com/images/thumbs/jenie.jpg"
			title = "Jenie (iOS)."
			description = "Search hotels, vacation rentals or hostels and share your experience through the Jenie mobile app."

		[[params.portfolio.gallery]]
			destination = "https://apps.apple.com/us/app/wrd-calculator/id1148696352"
			preview = "https://jjmtaylor.com/images/thumbs/wrd.jpg"
			title = "Wargame: Red Dragon Calculator (iOS & aOS)."
			description = "My first Ionic hybrid mobile application. It was written in Typescript using the Angular 2 framework and released simeltaneously to the Google Play Store and Apple App Store."

		[[params.portfolio.gallery]]
        	destination = "https://apps.apple.com/us/app/worldwide-equipment-guide-2015/id1392413944"
            preview = "https://jjmtaylor.com/images/thumbs/weg2015.jpg"
            title = "Worldwide Equipment Guide - 2015(iOS & aOS)."
            description = "A reboot of my 2012 Worldwide equipment guide.  This application was developed natively for iOS & Android using Swift & Kotlin respectively.  It is supported by a Kotlin Springboot API backed by a PostgreSQL database."

	[params.recentposts] 
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "I'm always open to new challenges and opportunities, or just to chat."

		address = [
			"Portland, OR",
			"United States"
		]
		phone = "503-410-4295"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "james.jm.taylor@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "About"
	url  = "about"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post"
	weight = 10

[[menu.main]]
	name = "Privacy Policy"
	url  = "privacy"
	weight = 15
