baseurl = "/"
languageCode = "en-us"
title = "James JM Taylor"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "James Taylor"
	description = "Blog and Portfolio for James Taylor, a native and hybrid android and iOS mobile developer."

	# Format dates with Go's time formatting
	date_format = "2018-01-26"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Hi!**  I'm James, a dedicated<br> polyglot mobile developer<br> based in Portland, OR."
		# The icons will be shown if you enter your username
		twitter = ""
		github = "jamesjmtaylor"
		dribbble = ""
		facebook = "James.Jordan.Moody.Taylor"
		googleplus = ""
		flickr = ""
		linkedin = "jamesjmtaylor"

		copyright = [
			"&copy; James Taylor",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Why me?"
		content = "Because you want a disciplined, innovative worker with a mean streak for pragmatism and a lifelong passion for learning. I take great pride in delivering delightful experiences to users of my mobile applications, and learned Sketch, Zeplin, and Lottie to make up for the lack of a designer on my personal projects. I quickly realized  though that an app is all for naught without a solid backend to support it.  So I used the Java from my native Android development to jumpstart into Spring Boot server development.  Now, with full command of the stack I've returned to delivering holistic applications for my users."
	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/weg2012.jpg"
			thumb = "thumbs/weg2012.jpg"
			title = "Worldwide Equipment Guide - 2012 (aOS)."
			description = "My first (and most popular) android app."

		[[params.portfolio.gallery]]
			image = "fulls/wrd.jpg"
			thumb = "thumbs/wrd.jpg"
			title = "Wargame: Red Dragon Calculator (iOS & aOS)."
			description = "My first Ionic hybrid mobile application."

		[[params.portfolio.gallery]]
        	image = "fulls/gwent.jpg"
            thumb = "thumbs/gwent.png"
            title = "Gwent (iOS)."
            description = "My capstone project at the Coding Dojo, where I studied the Swift programming language."

		[[params.portfolio.gallery]]
			image = "fulls/jenie.jpg"
			thumb = "thumbs/jenie.jpg"
			title = "Jenie (iOS)."
			description = "A hotel reservation application written in Swift that I built for the Portland startup, Jenie."

		[[params.portfolio.gallery]]
			image = "fulls/jenieConnect.jpg"
			thumb = "thumbs/jenieConnect.jpg"
			title = "Jenie Connect (iOS & aOS)."
			description = "A hotel sms messaging system written natively in Swift (iOS) and Java (aOS) for Jenie."

		[[params.portfolio.gallery]]
			image = "fulls/weg2015.jpg"
			thumb = "thumbs/weg2015.jpg"
			title = "Worldwide Equipment Guide - 2015 (iOS & aOS)."
			description = "A fullstack reboot of my original android WEG application.  Written in native Swift (iOS), Kotlin (aOS), and served from my own Spring Boot API."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "I'm always open to new challenges and opportunities, or just to chat."

		address = [
			"10926 SW Celeste Ln",
			"Portland, OR 97225",
			"United States"
		]
		phone = "503-410-4295"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "james.jm.taylor@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "About"
	url  = "about"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
